### ISSUE TITLE
grade command still expects JSON on stdout; incorrect line splitting

### ISSUE THREAD

**Issue by echuber2** [coursera/coursera_autograder#4]
The grade command seems to still expect the JSON to be emitted to stdout for local testing:

https://github.com/coursera/coursera_autograder/blob/227e2e46115d80a5f6278e1cabf1e949e40113c1/coursera_autograder/commands/grade.py#L81-L90

This means that v2 graders still need to output the JSON to stdout in addition to putting it at `/shared/feedback.json`, or else the local testing command won't work as expected.

Another issue is that the line splitting breaks JSON that are actually valid if they contain a linebreak anywhere, even between properties. For example, this should be okay:

```json
{
"fractionalScore": 0,
"feedback": "hello"
}
```

But the local test only accepts:

```json
{"fractionalScore": 0, "feedback": "hello"}
```

**Comment by vincenzobaz** [comment]
I have just encountered this issue: `grade local` fails because it tries to parse stdout instead of reading `feedback.json`.
I believe that this should be changed

**Comment by echuber2** [comment]
What I did for local testing purposes was make sure that stdout only contained a copy of the json. It's also picky about the formatting (as described above). You can set up your grader image to behave differently in local testing than it does on the server.

Since the server seems to have issues collecting all stdout in the instructor logs anyway, here's what I recommend: to stdout, print a copy of the json, only. Send all other diagnostics to stderr. This works well enough both for local testing and on the server.

**Comment by vincenzobaz** [comment]
Your solution is valid, I would however prefer to have the same behavior on `grade local` and on the servers, so that I can test behavior consistently.

Currently I am using a quick modification of the codebase that I propose on #6 coupled with the `dst-dir` argument

**Comment by sashi-coursera** [comment]
Thanks for this ticket and PR. We have approved and merged your PR. Thanks a lot for helping with this.
