### ISSUE TITLE
configure from courseraprogramming not available.

### ISSUE THREAD

**Issue by ethanluoyc** [coursera/coursera_autograder#5]
Hi,

Is there any plan to support the old `courseraprogramming configure` commands?

Thanks!

**Comment by vincenzobaz** [comment]
It was very useful to login and create the token in `~/.coursera` that could then be copied to CI machines

**Comment by echuber2** [comment]
It seems like the upload command creates tokens in `~/.coursera` after launching a login browser window.

**Comment by vincenzobaz** [comment]
Yes, but this means that I have to initiate an upload to generate the token.
With `courseraprogramming` I used to do `configure check-auth` which would create `~/.coursera`. Then I could copy the token to my CI server which would take care of uploading

**Comment by sashi-coursera** [comment]
Thank you for filing this issue. We will add support for this soon.

**Comment by sashi-coursera** [comment]
@vincenzobaz : we are addressing this as part of this [PR](https://github.com/coursera/coursera_autograder/pull/17), which we will merge soon. We hope this resolves this issue. Do let us know if you have any other comments/questions. Thank you. cc: @josephl310
